

·çÉ§LED£º
frontleft: LED3  PA2        frontright: LED2  PA1        backleft: LED4  PA3    backright: LED1  PA0

IRAD:
front: IRAD0 PA5     back: IRAD2 PA7      left: IRAD1 PA6     right:  IRAD3 PB8

CS:
MPU: PB10   T2C3
BMP: PB12   T1_BKIN

SPI: SPI2
SCK PB13
SDO PB14
SDI PB15

Motor:
frontleft: PA8  T1C1        frontright: PA11 T1C4         backleft:  PA9 T1C2      backright: PA10 T1C3

Bluetooth:(HM-13)
Usart1  Tx: PB6 T4C1        Rx: PB7 T4C2
